<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageId>Wangdefa.Memory</PackageId>
		<Version>1.1.2</Version>
		<Authors>wangdefa</Authors>
		<Description>本地优先的 Agent 五层记忆体组件</Description>
		<PackageTags>agent;memory;ai;local;sqlite</PackageTags>
		<PackageProjectUrl>https://github.com/VinsonWild/Wangdefa.Memory</PackageProjectUrl>
		<RepositoryUrl>https://github.com/VinsonWild/Wangdefa.Memory</RepositoryUrl>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
	</ItemGroup>

	<ItemGroup>
		<None Include="../README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

</Project>